name: calculator_app
description: A simple calculator app using Flutter.

publish_to: 'none' # Remove this line if it's missing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
